import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Roboto } from "next/font/google";
import Header from "@/app/header/page";
import Footer from "./footer/page";
import AsponsorBy from "@/app/asponsor/page";
import CopyRight from "./copyRight/page";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
        <AsponsorBy />
        <CopyRight />
      </body>
    </html>
  );
}
